language: node_js
node_js:
- '11'
addons:
  ssh_known_hosts:
  - 139.224.223.179
services:
  - docker
cache:
  directories:
  - node_modules
install:
- docker build -t kuni .
- docker restart rungame
before_script: 
script:
- docker ps | grep -q kuni
after_script:
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_02d903fb5ebd_key -iv $encrypted_02d903fb5ebd_iv
  -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 ~/.ssh/id_rsa
- ssh-add ~/.ssh/id_rsa
