
language: node_js
# nodejs版本
node_js: 
    - '11'
 
# Travis-CI Caching
cache:
  directories:
    - node_modules
 
# S: Build Lifecycle
install:
  - npm install
 
before_script:
 
# 无其他依赖项所以执行npm run build 构建就行了
script:
  - npm run build
 
after_script:
  - cd ./output
  - git init
  - git config user.name "${kuniName}"
  - git config user.email "${kuniEmail}"
  - git add .
  - git commit -m "Update tools"
  - git push --force --quiet "https://${kuniTOKEN}@${kuniRef}" master:${P_BRANCH}
# E: Build LifeCycle
 
#指定分支，只有指定的分支提交时才会运行脚本
branches:
  only:
    - master
